### PR TITLE
Refactor serialization to converter.

### PR DESCRIPTION
**Pull request by gvieira**
This follows the patterns of the Go and Java SDKs and allows
interoperability between Ruby and the other SDKs by converting arguments
to/from payloads in the same way.

Serialisation of protobufs has been left as-is because it is not
affected by interoperability issues.

### CODE REVIEW

**Comment by gvieira** [comment]
After cherry-picking it from Rob's branch, I've diffed his branch, then this branch, and diffed the diffs to make sure everything was in place. Even though some things are a bit different, changes are all correctly applied.

**Comment by gvieira** [comment]
@robholland Can you check 8eb4a755c258ea347b50ee2e8d60bc273d7fefa9? It was still using the old `to_proto` and I've followed the same pattern, but 🤷.

**Comment by robholland** [comment]
Just check https://github.com/opus-grove/temporal-ruby/blob/opus-main/lib/temporal/client/serializer/continue_as_new.rb

**Comment by gvieira** [comment]
Cool! Just a different `require` and that's it. Ready for review!

**Review by ayrton — APPROVED** [review]
Let's squash them as one commit when merging so we get a relatively straight forward history. As changes get merged into upstream we can easily rebase/merge

**Pull request merged**
